version: '3'
services:
    db:
        container_name: db
        image: mysql:8.0.22
        restart: on-failure
        tty: true
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - "db_app:/var/lib/mysql"
        networks:
            - db
    php:
        container_name: php
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
            args:
                PROJECT_NAME: ${PROJECT_NAME}
                ENV: ${ENV}
        restart: on-failure
        tty: true
        ports:
            - 9000:9001
        volumes:
            - ./logs/symfony:/var/www/${PROJECT_NAME}/var/log:cached
            - ./logs/php:/var/log/php7
            - ./symfony:/var/www/${PROJECT_NAME}:cached
        depends_on: 
            - db
        networks:
            - db
            - php
    nginx:
        container_name: nginx
        restart: on-failure
        tty: true
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
            args:
                SERVER_NAME: ${SERVER_NAME}
                PROJECT_NAME: ${PROJECT_NAME}
                USER: ${USER}
        ports:
            - 80:80
            - 443:443
        depends_on: 
            - php
        networks:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - ./symfony:/var/www/${PROJECT_NAME}:cached
    redis:
        container_name: redis
        image: redis:alpine
        restart: on-failure
        tty: true
        ports:
            - 6379:6379
        networks:
            - php
volumes:
    db_app:

networks:
    db:
    php: